FROM composer:2 AS dependencies
WORKDIR /app
COPY composer.json ./
RUN composer install --no-dev --no-interaction --no-progress --optimize-autoloader --ignore-platform-reqs

FROM dunglas/frankenphp:1-php8.2-alpine
WORKDIR /app
RUN install-php-extensions pdo_mysql
COPY --from=dependencies /app/vendor ./vendor
COPY Caddyfile /etc/caddy/Caddyfile
COPY . /app
ENV PORT=80
CMD ["frankenphp", "run", "--config", "/etc/caddy/Caddyfile"]
